### ISSUE TITLE
Add prototypes to treemap.h

### ISSUE THREAD

**Issue by bakedSpaceTime** [CapU-CompSci/MapADT-220-2019#141]

**Comment by bakedSpaceTime** [comment]
The function prototypes from project spec

**Comment by gracehumer** [comment]
added all prototypes from hashmap.h that need to be identical

**Comment by gracehumer** [comment]
need to add constructor/destructor prototypes. Am working on them

**Comment by gracehumer** [comment]
All prototypes added. :)

**Comment by gracehumer** [comment]
Minor edit to destructor function - added better comment
